source:
  url: https://github.com/smith-chem-wisc/FlashLFQ/releases/download/{{version}}/FlashLFQ.zip
  sha256: tbd

package:
  name: flashlfq
  version: 1.2.1

build:
  noarch: generic
  number: 0

requirements:
  build:
  run:
    - dotnet-runtime =5.0

test:
  commands:
    - FlashLFQ --help

about:
  home: https://github.com/smith-chem-wisc/FlashLFQ
  license: LGPL-3.0
  summary: ultrafast label-free quantification algorithm for mass-spectrometry proteomics
  license_family: GPL
  
extra:
  identifiers:
   - doi:10.1021/acs.jproteome.7b00608
